name: phenoplier
channels:
  - conda-forge
dependencies:
  - ipython=7.*
  - ipywidgets
  - jupyterlab=2.2.*
  - matplotlib=3.3.*
  - nodejs=14.*
  - numpy=1.19.*
  - pandas=1.1.*
  - pip
  - pytest=6.1.*
  - python=3.8.*
  - pyyaml=5.3.*
  - r-base=3.6.*
  - r-devtools=2.*
  - r-essentials
  - rpy2=3.3.*
  - scikit-learn=0.23.*
  - scipy=1.5.*
  - seaborn=0.11.*
  - tqdm=4.54.*
  - umap-learn=0.4.*
  # obonet deps:
  - networkx=2.5.*
  - pip:
    - obonet==0.2.*
