name: phenoplier
channels:
  - conda-forge
  - defaults
dependencies:
  - fastparquet
  - ipython
  - ipywidgets
  - jupyterlab
  - jupytext
  - matplotlib
  # obonet deps:
  - networkx
  #
  - nodejs
  - numpy
  - pandas
  - papermill
  - pip
  - openpyxl
  - pytables
  - pytest
  - python=3.10.*
  - python-snappy
  - pyyaml
  - r-base=4.2.*
  - r-devtools
  - r-essentials
  - r-reticulate
  - r-svglite
  - requests
  - rpy2
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tabulate
  - tqdm
  - umap-learn
  - pip:
    - obonet

