name: phenoplier
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyterlab
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - pip
  - pytest
  - python=3.8.*
  - pyyaml
  - r-base=3.6.*
  - r-devtools
  - r-essentials
  - rpy2
  - scikit-learn
  - scipy
  - seaborn
  - umap-learn
  # obonet deps:
  - networkx
  - pip:
    - obonet
