name: phenoplier
channels:
  - conda-forge
dependencies:
  - ipython
  - ipywidgets
  - jupyterlab
  - jupytext
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - papermill
  - pip
  - fastparquet
  - openpyxl
  - pytables
  - pytest
  - python=3.8.*
  - python-snappy
  - pyyaml
  - requests
  - r-base=3.6.*
  - r-devtools
  - r-essentials
  - r-reticulate
  - r-svglite
  - rpy2
  - scikit-learn
  - scipy
  - seaborn
  - tabulate
  - tqdm
  - umap-learn
  # obonet deps:
  - networkx
  - pip:
    - obonet
